# Rustfmt configuration for code formatting (stable features only)
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
merge_derives = true
match_block_trailing_comma = false